FROM alpine
ARG NITIN_CREDS_USR
ARG NITIN_CREDS_PSW
# RUN echo "Username is ${USER}"
# RUN echo "Password is ${PASSWD}"
# RUN export USER=${USER}
# RUN export PASSWD=${PASSWD}
ENV NITIN_CREDS_USR=${NITIN_CREDS_USR}
ENV NITIN_CREDS_PSW=${NITIN_CREDS_PSW}
